codecov:

coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      unit:
        target: 80%
        threshold: 3%
        base: auto
        flags:
          - unit
