# coverage:
#   status:
#     project:
#       default:
#         target: 80%
#         threshold: 3%
#         base: auto
#         flags:
#           - unit
coverage:
  status:
    project: true
    patch: true
comment:
  layout: 'header, diff, flags, files, footer'
