version: '3'

vars:
  UNIT_TEST_DIR: UnitTest
  UNIT_TEST_COVERAGE_THRESHOLD: 50
  UNIT_TEST_TARGETS: Lithium,LithiumTestHelper

tasks:
  default:
    desc: 'Unit Test the library'
    cmds:
      - task: unit:watch

  unit:
    desc: 'Unit Test the library'
    cmds:
      - dotnet test {{.UNIT_TEST_DIR}} {{.CLI_ARGS}}

  unit:watch:
    desc: 'Unit Test the library and watch for changes'
    cmds:
      - dotnet watch test --project {{.UNIT_TEST_DIR}} {{.CLI_ARGS}}

  unit:cover:
    desc: 'Unit Test the library and show coverage'
    cmds:
      - ./scripts/local/cover.sh {{.UNIT_TEST_DIR}} {{.UNIT_TEST_TARGETS}} {{.UNIT_TEST_COVERAGE_THRESHOLD}}
